version: '3'
services:
  mysql:
    image: mysql:5.7.22
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=starwars
      - MYSQL_USER=starwars
      - MYSQL_PASSWORD=starwars